select
    CUSTOMER_ID as customer_id,
    CUSTOMER_FIRST_NAME as first_name,
    CUSTOMER_LAST_NAME as last_name,
    CUSTOMER_EMAIL as email,
    CUSTOMER_CITY as city,
    CUSTOMER_STATE as state,
    CUSTOMER_ZIP as zip_code
from OLIVIABROCKMAN.RAW_ECOESSENTIALS_PG_ECOESSENTIALS_TRANSACTIONAL_DB.CUSTOMER